#!/usr/bin/env bash
set -euo pipefail

mkdir -p \
  "$HOME/.local/bin" \
  "$HOME/Documents" \
  "$HOME/Downloads" \
  "$HOME/Pictures" \
  "$HOME/Projects" \
  "$HOME/Pictures/wallpapers" \
  "$HOME/Pictures/screenshots"
