#!/usr/bin/env bash
set -euo pipefail

# Source libs
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../lib" && pwd)"
source "$SCRIPT_DIR/logging"

mkdir -p \
  "$HOME/.local/bin" \
  "$HOME/Documents" \
  "$HOME/Downloads" \
  "$HOME/Pictures" \
  "$HOME/Projects" \
  "$HOME/Pictures/wallpapers" \
  "$HOME/Pictures/screenshots"
