#!/usr/bin/env bash
[[ "${OS:-}" != "macos" ]] && return

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# optional: Brewfile
if [[ -f "$HOME/.Brewfile" ]]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi
